# This is an example capabilities file.  Please note that RAIS will not check
# custom capabilities for validity; as such, if you claim something is enabled
# which RAIS doesn't support, such as WEBP output, IIIF image clients may make
# invalid requests RAIS won't handle.
#
# All values below reflect the state of RAIS's capabilities as of August, 2018.
# Note that Gif output is disabled by default, but may be enabled if desired.
# It is generally too slow for a production server, however.
RegionByPx = true
RegionByPct = true
RegionSquare = true

SizeByWhListed = true
SizeByW = true
SizeByH = true
SizeByPct = true
SizeByWh = true
SizeByForcedWh = true
SizeAboveFull = true

RotationBy90s = true
Mirroring = true

Default = true
Color = true
Gray = true
Bitonal = true

Jpg = true
Png = true
Gif = false
Tif = true

BaseURIRedirect = true
Cors = true
JsonldMediaType = true
