# This file describes how you could add datadog as a container to the RAIS
# stack.  You can test this out by setting up the datadog DD_API_KEY in .env
# and running:
#
#     ./scripts/buildrun.sh make
#     ./scripts/buildrun.sh make datadog
#     docker-compose -f docker-compose.yml -f docker-compose.datadog.yml up -d
#     docker-compose -f docker-compose.yml -f docker-compose.datadog.yml logs -f
#     docker-compose -f docker-compose.yml -f docker-compose.datadog.yml down
#
# Take note of the first two commands: you *must manually compile* RAIS as
# well as the datadog plugin!
#
# Also take note that *all* docker-compose commands must specify the files
# unless you either merge this configuration with docker-compose.yml or put
# this into docker-compose.override.yml.  For quick testing, an alias may help:
#
#     alias ddog='docker-compose -f docker-compose.yml -f docker-compose.datadog.yml'
version: "3.4"
services:
  rais:
    environment:
      - RAIS_DATADOGADDRESS=dd-agent:8126
    depends_on:
      - dd-agent

  dd-agent:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    expose:
      - 8126
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
