# This describes a self-contained demo of RAIS, using Apache to serve up the
# static pages.  This isn't a production configuration file!!
#
# Put JP2s into docker/images and the apache entrypoint script will add them to
# the images served by from RAIS.
version: "3"

volumes:
  gopath: {}
  gocache: {}

services:
  # Run this directly if you need to build the binaries: docker-compose up rais-build
  rais-build:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.build
    volumes:
      - ./:/opt/rais-src:rw
      - ./docker/images:/var/local/images:ro
      - gopath:/usr/local/go
      - gocache:/root/.cache/go-build
    command: make

  rais:
    image: uolibraries/rais
    environment:
      - URL
      - RAIS_ADDRESS
      - RAIS_LOGLEVEL
      - RAIS_TILEPATH
      - RAIS_IIIFURL
      - RAIS_INFOCACHELEN
      - RAIS_TILECACHELEN
      - RAIS_IMAGEMAXAREA
      - RAIS_IMAGEMAXWIDTH
      - RAIS_IMAGEMAXHEIGHT
      - RAIS_S3CACHE
      - RAIS_S3ZONE
      - RAIS_S3BUCKET
      - AWS_SHARED_CREDENTIALS_FILE=/etc/aws.credentials
    volumes:
      - ./bin/rais-server:/opt/rais/rais-server:ro
      - ./bin/plugins:/opt/rais/plugins:ro
      - ./docker/images:/var/local/images:ro
      - ./rais-example.toml:/etc/rais-template.toml:ro
      - ./cap-max.toml:/etc/rais-capabilities.toml:ro
      - ./docker/demo-rais-entry.sh:/entrypoint.sh:ro
      - ./docker/s3credentials:/etc/aws.credentials
      - /tmp:/tmp
    entrypoint: /entrypoint.sh
    ports:
      - 12415:12415

  web:
    image: nginx:1.15
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/images:/var/local/images:ro
      - ./docker/static:/static:ro
      - ./docker/demo-web-entry.sh:/entrypoint.sh:ro
    entrypoint: /entrypoint.sh
    depends_on:
      - rais
    ports:
      - 80:80
