# Copy this to /etc/rais.toml and customize as needed to avoid specifying
# config on the command line in your init.d / upstart / etc. scripts

# At a minimum, address must be specified
Address = ":12415"

# Set this to the path to the JP2 files if you need to override the default
TilePath = "/var/local/images"

# If you want to enable IIIF support, set this to the desired URL - it *must*
# resolve to the tile server
IIIFURL = "http://localhost:12415/iiif"

# Set this to 0 to avoid caching IIIF Info requests, or set it higher to cache
# more requests.  The overhead for caching is very small; probably under 500
# bytes of RAM per cached item.  But the CPU / IO overhead for generating info
# requests dynamically is pretty small as well.
InfoCacheLen = 10000
