# Copy this to /etc/rais.toml and customize as needed to avoid specifying
# config on the command line in your init.d / upstart / etc. scripts

# Address: Optional, defaults to ":12415".  This is where RAIS listens for
# traffic.  The default value causes RAIS to accept anything that talks to port
# 12415 on the server.
#
# Env: RAIS_ADDRESS
# CLI: --address
Address = ":12415"

# TilePath: Required.  Set this to the path where images can be found.  Note
# that docker uses an environment setting to force this to "/var/local/images",
# and environment settings override config file settings.
#
# Env: RAIS_TILEPATH
# CLI: --tile-path
TilePath = "/var/local/images"

# IIIFURL: Optional.  If you want to enable IIIF support, set this to the
# desired URL - it *must* resolve to the tile server.  If this isn't set, only
# the legacy handlers will work.
#
# Env: RAIS_IIIFURL
# CLI: --iiif-url
IIIFURL = "http://192.168.56.99:12415/iiif"

# InfoCacheLen: Optional, defaults to 10000.  Set this to 0 to avoid caching
# IIIF Info requests, or set it higher to cache more requests.  The overhead
# for caching is very small; probably under 500 bytes of RAM per cached item.
# But the CPU / IO overhead for generating info requests dynamically is pretty
# small as well.
#
# Env: RAIS_INFOCACHELEN
# CLI: --iiif-info-cache-size
InfoCacheLen = 10000

# CapabilitiesFile: Optional, allows removal of undesired capabilities, such as
# CORS support or GIF output.  See cap-max.toml for an example.
# CapabilitiesFile = "/etc/rais-capabilities.toml"

# TileCacheLen: Optional, defaults to 0.  Set this to the *number* of tiles
# you'd like to cache.  Currently the cache is set to only store specific types
# of requests in order to only cache JPG tiles.  The amount of RAM which may be
# used will vary greatly depending on what ends up being cached.  For
# newspapers, it's not unreasonable for a tile to be as large as 100k, and for
# a single page to have up to 200 unique 1024x1024 tiles.  Therefore a
# 10,000-item cache could use as much as a gig of RAM, and still only hold 50
# pages.  In practice, this is likely to only be useful for caching small
# exhibits or else sites that have one or a few "featured" images.
TileCacheLen = 0
