version: "3.4"

networks:
  internal:
  external:

services:
  rais:
    image: uolibraries/rais
    environment:
      - RAIS_S3CACHE=/var/tmp/rais/s3
      - RAIS_IIIFURL
      - RAIS_S3ZONE
      - RAIS_S3BUCKET
      - RAIS_S3ENDPOINT
      - RAIS_PLUGINS
      - RAIS_INFOCACHELEN
      - RAIS_TILECACHELEN
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - /tmp:/tmp
    networks:
      internal:

  s3demo:
    build:
      context: ..
      dockerfile: ./s3demo/Dockerfile
    environment:
      - RAIS_S3ZONE
      - RAIS_S3BUCKET
      - RAIS_S3ENDPOINT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    networks:
      internal:

  web:
    image: nginx:1.15
    volumes:
      - ../../:/opt/rais-image-server:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - rais
      - s3demo
    ports:
      - 80:80
    networks:
      internal:
      external:
