version: "3.4"

services:
  rais:
    image: uolibraries/rais
    environment:
      - RAIS_LOGLEVEL=DEBUG
      - RAIS_IIIFURL=http://localhost:12415/iiif
      - RAIS_S3CACHE=/var/tmp/rais/s3
      - RAIS_S3ZONE={{.Zone}}
      - RAIS_S3BUCKET={{.Bucket}}
      - AWS_ACCESS_KEY_ID={{.KeyID}}
      - AWS_SECRET_ACCESS_KEY={{.SecretKey}}
      # For demo purposes, we don't want to cache anything in memory, otherwise
      # people think Rais + S3 is some miracle solution
      - RAIS_INFOCACHELEN=0
      - RAIS_TILECACHELEN=0
    ports:
      - 12415:12415
