version: "3.4"

networks:
  internal:
  external:

volumes:
  minio-data:

services:
  rais:
    image: uolibraries/rais
    environment:
      - RAIS_S3CACHE=/var/tmp/rais/s3
      - RAIS_S3ZONE=us-west-2
      - RAIS_S3ENDPOINT=http://minio:9000
      - RAIS_PLUGINS=s3-images.so,json-tracer.so
      - AWS_ACCESS_KEY_ID=awss3key
      - AWS_SECRET_ACCESS_KEY=awsappsecret
    volumes:
      - /tmp:/tmp
    networks:
      internal:

  s3demo:
    build:
      context: ..
      dockerfile: ./s3demo/Dockerfile
    environment:
      - RAIS_S3CACHE=/var/tmp/rais/s3
      - RAIS_S3ZONE=us-west-2
      - RAIS_S3ENDPOINT=http://minio:9000
      - RAIS_S3BUCKET=rais
      - RAIS_PLUGINS=s3-images.so,json-tracer.so
      - AWS_ACCESS_KEY_ID=awss3key
      - AWS_SECRET_ACCESS_KEY=awsappsecret
    networks:
      internal:

  web:
    image: nginx:1.15
    volumes:
      - ../../:/opt/rais-image-server:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - rais
      - s3demo
    ports:
      - 80:80
    networks:
      internal:
      external:

  # minio for testing against a local S3-compatible API
  minio:
    image: minio/minio
    volumes:
      - minio-data:/data
    command: minio server /data
    expose:
      - 9000
    environment:
      - MINIO_ACCESS_KEY=awss3key
      - MINIO_SECRET_KEY=awsappsecret
    ports:
      - 9000:9000
    networks:
      internal:
      external:
